apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx.yaml
  - cert-manager.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - promtail.yaml
  - tempo.yaml
  - otel-collector.yaml
  - gatekeeper.yaml
  - grafana-dashboards.yaml
