config:
  snippets:
    extraScrapeConfigs: []
  clients:
    - url: http://loki-stack:3100/loki/api/v1/push

# Disable scanning all host logs
extraVolumes: []
extraVolumeMounts: []

# Use ONLY Kubernetes pod logs
pipelineStages:
  - cri: {}

scrapeConfigs:
  - jobName: kubernetes-pods
    pipelineStages:
      - cri: {}
    staticConfigs:
      - targets:
          - localhost
        labels:
          job: kubernetes-pods
          __path__: /var/log/pods/*/*/*.log