apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - templates/requiredlabels.yaml
  - constraints/requiredlabels.yaml
  - templates/requiredlimits.yaml
  - constraints/requiredlimits.yaml